blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('blog/<int:pk>/edit/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import HomeListView, ContactsView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    CategoryListView

app_name = CatalogConfig.name

urlpatterns = [
    path('', HomeListView.as_view(), name='home'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('product/<int:pk>/', cache_page(20)(ProductDetailView.as_view()), name='product'),
    path('create/', ProductCreateView.as_view(), name='create_product'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('category', CategoryListView.as_view(), name='list_category'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='Наименование')
    description = models.CharField(max_length=150, verbose_name='Описание')


    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['name']



class Product(models.Model):
    name = models.CharField(max_length=50, verbose_name='Наименование')
    description = models.CharField(max_length=150, verbose_name='Описание')
    image = models.ImageField(upload_to='product/photo', verbose_name='Фото', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, verbose_name='Категория', **NULLABLE, related_name="products")
    price_per_purchase = models.DecimalField(max_digits=30, decimal_places=2, verbose_name='Цена за покупку')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')

    owner = models.ForeignKey(User, verbose_name="Владелец", **NULLABLE, on_delete=models.SET_NULL)

    is_unpublish = models.BooleanField(default=False, verbose_name="Статус публикации продукта")

    def  __str__(self):
        return f'{self.name} {self.description} {self.category}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ['name',]
        permissions = [
            ("is_unpublish_product", "Is unpublish product"),
            ("change_description_product", "Change product description"),
            ("change_category_product", "Change product category")
        ]



class Version(models.Model):
    product = models.ForeignKey(Product, related_name="version", on_delete=models.SET_NULL, **NULLABLE, verbose_name="Продукт")
    version_number = models.IntegerField(verbose_name="Номер версии")
    version_name = models.CharField(max_length=50, verbose_name="Название версии")
    current_version = models.BooleanField(default=True, verbose_name="Признак текущей версии")

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

    def __str__(self):
        return self.version_name

catalog/forms.py
from django.forms import ModelForm, forms, BooleanField

from catalog.models import Product, Version


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fild_name, fild in self.fields.items():
            if isinstance(fild, BooleanField):
                fild.widget.attrs['class'] = "form-check-input"
            else:
                fild.widget.attrs['class'] = "form-control"


class ProductForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        exclude = ('created_at', 'updated_at', 'owner', )


    def clean_name(self):
        clean_name = self.cleaned_data['name']

        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        for word in forbidden_words:
            if word in clean_name.lower():
                raise forms.ValidationError('Данное слово нельзя использовать в названии')
        return clean_name


    def clean_description(self):
        clean_description = self.cleaned_data['description']

        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        for word in forbidden_words:
            if word in clean_description.lower():
                raise forms.ValidationError(f'{word} - это слово нельзя использовать в описании')
        return clean_description

class ProductModeratorForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        fields = ('description', 'category', 'is_unpublish', )

class VersionForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Version
        fields = "__all__"

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView

from catalog.forms import ProductForm, VersionForm, ProductModeratorForm
from catalog.models import Product, Version, Category
from catalog.services import get_category_from_cache


class HomeListView(ListView):
    model = Product

    context_object_name = 'products'

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data()
        version_dict = {}
        products = context_data['products']
        for product in products:
            product_version = Version.objects.filter(product=product, current_version=True).first()
            version_dict[product.name] = product_version
        context_data['current_versions'] = version_dict
        return context_data



class ProductDetailView(DetailView):
    model = Product



class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')

    def form_valid(self, form):
        product = form.save()
        user = self.request.user
        product.owner = user
        product.save()
        return super().form_valid(form)




class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')



    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        ProductFormset = inlineformset_factory(Product, Version, VersionForm, extra=1)
        if self.request.method == "POST":
            context_data['formset'] = ProductFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = ProductFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))


    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if user.has_perm("catalog.is_unpublish_product") and user.has_perm("catalog.change_description_product") and user.has_perm("catalog.change_category_product"):
            return ProductModeratorForm
        raise PermissionDenied



class ContactsView(TemplateView):
    """Класс для вывода страницы с контактами"""
    template_name = "catalog/contacts.html"


class CategoryListView(ListView):
    model = Category

    def get_queryset(self):
        return get_category_from_cache()

catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
{% include 'catalog/includes/inc_main_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto bg-danger text-center text-white">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - интернет магазин цифровой техники</p>
</div>

{% block content %}
{% endblock %}

<footer class="pt-4 my-md-5 pt-md-5 bg-danger border-top">
    <div class="row">
        <div class="col-12 col-md">
            SkyStore
            <small class="d-block mb-3 text-muted">&copy; 2024</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="col-12 mb-5">
    <div class="bg-danger row text-center">
        {% for category in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ category.name }}</h4>
                </div>
                <div class="card-body">
                    <p class="text-warning">{{ category.description }}</p>

                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Россия</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91111111111</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>г. Москва, ул. Московская, д. 31</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <div class="bg-danger row text-center">
        {% for product in products %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                </div>
                <div class="card-body">
                    <h1 class="text-warning">{{ product.price_per_purchase }} ₽</h1>
                    <p class="text-justify">{{ product.description|truncatechars:100 }}</p>
                    <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                       href="{% url 'catalog:product' product.pk %}">Подробнее</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load my_tags %}


{% block content %}

<div class="album py-5 bg-body-tertiary">
    <div class="container">

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{ product.photo | media_filter }}">
                    <div class="card-body">
                        <p class="card-text">{{ object.description }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                                   href="">Купить</a>
                                {% if perms.catalog.is_unpublish_product and perms.catalog.change_description_product and perms.catalog.change_category_product or user == object.owner %}
                                <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                                   href="{% url 'catalog:update_product' object.pk %}">Редактировать</a>
                                {% endif %}
                                <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                                   href="{% url 'catalog:home' %}">Назад</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load my_tags %}


{% block content %}

<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card"
            <div class="card-header">
                <h3 class="card-title">
                    Добавление товара
                </h3>
                <div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-sm btn-outline-secondary">Сохранить</button>
                    </div>
                </div class="card-footer">
            </div>
        </div>
        <div class="col-6">
            <div class="card"
            <div class="card-header">
                <h3 class="card-title">
                    Добавление версии товара
                </h3>
                <div>
                    <div class="card-body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                        {{ form.as_p }}
                        {% endfor %}
                        <button type="submit" class="btn btn-sm btn-outline-secondary">Сохранить</button>
                    </div>
                </div class="card-footer">
            </div>
        </div>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="col-12 mb-5">
    {% if user.is_authenticated %}
    <a class="btn btn-outline-primary" href="{% url 'catalog:create_product' %}">Добавить продукт</a>
    {% endif %}
    <div class="bg-danger row text-center">
        {% for product in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                    {% if product.version.all %}
                    {% for version in product.version.all %}
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        {% if version.current_version %}
                        <li> Название версии: {{version.version_name}}</li>
                        <li> Номер версии: {{version.version_number}}</li>
                        {% endif %}
                    </ul>
                    {% endfor %}
                    {% else %}
                    <li> Нет активной версии</li>
                    {% endif %}
                </div>
                <div class="card-body">
                    <h1 class="text-warning">{{ product.price_per_purchase }} ₽</h1>
                    <p class="text-justify">{{ product.description|truncatechars:100 }}</p>
                    <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                       href="{% url 'catalog:product' product.pk %}">Подробнее</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}